### ISSUE TITLE
Move the API Key to config file and read from there

### ISSUE THREAD

**Issue by henriquelbsouza** [SpaceOgre/smarttv-twitch#4]
As the title says, it would be easier to move the apikey to the config file so we could change only in one place (And in the future, maybe type it when open the app somehow and store it on localStorage, can be done with #3 )

**Comment by SpaceOgre** [comment]
I did a fix in #5 that might work, I think a Accept header was missing for the calls in SceneChannel and that messed it up. According to the documentation this header is needed for v5 if the Client-ID is old:
`xmlHttp.setRequestHeader('Accept', 'application/vnd.twitchtv.v5+json');`

But I wont be able to test it myself since I don't get much TV access at home atm (Kids and stuff) so if you have the time please test and let me know. If it works then the API key fix is not necessary.

**Comment by SpaceOgre** [comment]
Fixed in #7
